# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
notifications:
  email: false
addons:
  apt:
    packages:
    - hdf5-tools
before_script:
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; brew link --overwrite gcc; brew install hdf5; fi
after_success:
  # push coverage results to Coveralls
    - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("FlashWeave")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
